export const primaryColor = "#22c55e"; // Tailwind's green-500
export const secondaryColor = "#16a34a"; // Tailwind's green-600
export const accentColor = "#10b981"; // Tailwind's green-400
export const headerBackgroudColor="#008236"; // Dark Green green-700
export const backgroundColor = "#f9fafb"; // Tailwind's gray-50
export const textColor = "#111827"; // Tailwind's gray-900
export const borderColor = "#d1d5db"; // Tailwind's gray-300
export const shadowColor = "rgba(0, 0, 0, 0.1)"; // Light shadow
export const hoverColor = "#6ee7b7"; // Tailwind's green-300
export const disabledColor = "#9ca3af"; // Tailwind's gray-400
export const errorColor = "#ef4444"; // Tailwind's red-500
export const successColor = "#22c55e"; // Tailwind's green-500
export const warningColor = "#f59e0b"; // Tailwind's yellow-500
export const infoColor = "#3b82f6"; // Tailwind's blue-500
export const fontFamily = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
export const borderRadius = "0.5rem"; // 8px
export const transitionDuration = "0.3s";
export const transitionTimingFunction = "ease-in-out";
export const zIndexModal = 1000;
export const zIndexDropdown = 900;
export const zIndexTooltip = 800;
export const zIndexSticky = 700;
export const maxWidthContainer = "1200px";
export const spacingUnit = "1rem"; // 16px
export const headerHeight = "60px";
export const footerHeight = "40px";
export const sidebarWidthExpanded = "250px";
export const sidebarWidthCollapsed = "80px";    
export const boxShadow = `0 4px 6px -1px ${shadowColor}, 0 2px 4px -1px ${shadowColor}`;
export const boxShadowHover = `0 10px 15px -3px ${shadowColor}, 0 4px 6px -2px ${shadowColor}`;
export const inputPadding = "0.5rem 1rem"; // 8px 16px
export const inputBorderColor = borderColor;
export const inputFocusBorderColor = primaryColor;
export const buttonPadding = "0.5rem 1.5rem"; // 8px 24px
export const buttonFontWeight = "600";
export const buttonHoverBackgroundColor = hoverColor;
export const buttonDisabledBackgroundColor = disabledColor;
export const cardPadding = "1.5rem"; // 24px
export const cardBorderRadius = borderRadius;
export const cardBoxShadow = boxShadow;
export const cardBoxShadowHover = boxShadowHover;
export const modalPadding = "2rem"; // 32px
export const modalBorderRadius = borderRadius;
export const modalBoxShadow = boxShadow;
export const tooltipPadding = "0.5rem 1rem";
export const tooltipBorderRadius = borderRadius;
export const tooltipBackgroundColor = textColor;
export const tooltipTextColor = "#ffffff"; // White
export const dropdownPadding = "0.5rem 0";
export const dropdownBorderRadius = borderRadius;
export const dropdownBoxShadow = boxShadow;
export const tableHeaderBackgroundColor = primaryColor;
export const tableRowHoverBackgroundColor = hoverColor;
export const tableBorderColor = borderColor;
export const alertPadding = "1rem 1.5rem";
export const alertBorderRadius = borderRadius;
export const alertBoxShadow = boxShadow;
export const alertSuccessBackgroundColor = successColor;
export const alertErrorBackgroundColor = errorColor;
export const alertWarningBackgroundColor = warningColor;
export const alertInfoBackgroundColor = infoColor;
export const navLinkPadding = "0.75rem 1.5rem";
export const navLinkHoverBackgroundColor = hoverColor;
export const navLinkActiveBackgroundColor = primaryColor;
export const badgePadding = "0.25rem 0.75rem";
export const badgeBorderRadius = "9999px"; // Full pill
export const badgeBackgroundColor = primaryColor;
export const badgeTextColor = "#ffffff"; // White   
export const breadcrumbSeparator = ">";
export const breadcrumbLinkColor = primaryColor;
export const breadcrumbLinkHoverColor = hoverColor;
export const formLabelFontWeight = "600";
export const formErrorColor = errorColor;
export const formSuccessColor = successColor;
export const paginationButtonPadding = "0.5rem 1rem";
export const paginationButtonHoverBackgroundColor = hoverColor;
export const paginationButtonActiveBackgroundColor = primaryColor;
export const sidebarBackgroundColor = "#ffffff"; // White
export const sidebarTextColor = textColor;
export const sidebarHoverBackgroundColor = hoverColor;
export const sidebarActiveBackgroundColor = primaryColor;
export const topbarBackgroundColor = "#ffffff"; // White
export const topbarTextColor = textColor;
export const topbarBoxShadow = boxShadow;
export const footerBackgroundColor = "#f3f4f6"; // Tailwind's gray-100
export const footerTextColor = textColor;
export const cardBackgroundColor = "#ffffff"; // White
export const inputBackgroundColor = "#ffffff"; // White
export const inputTextColor = textColor;
export const buttonBackgroundColor = primaryColor;
export const buttonTextColor = "#ffffff"; // White
export const linkColor = primaryColor;
export const linkHoverColor = hoverColor;
export const disabledTextColor = "#6b7280"; // Tailwind's gray-500
export const tableHeaderTextColor = "#ffffff"; // White
export const tableRowTextColor = textColor;

export const overlayBackgroundColor = "rgba(0, 0, 0, 0.5)"; // Semi-transparent black
export const modalZIndex = zIndexModal;
export const dropdownZIndex = zIndexDropdown;
export const tooltipZIndex = zIndexTooltip;
export const stickyZIndex = zIndexSticky;

export const breakpoints = {
    sm: "640px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    '2xl': "1536px",
};  
